server:
  port: 9090
  servlet:
    context-path: /shop-manager

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 161017
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      max-idle: 20
      min-idle: 1
      max-wait: 60000
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;character=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/
    request-context-attribute: request
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    settings:
      tag_syntax: auto_detect
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: #.##
      boolean_format: true,flase
      template_exception_handler: html_debug

  dubbo:
    server: true
    application:
      name: rpc-provider
    registry:
      address: zookeeper://localhost:2181?backup=localhost:2182,localhost:2183
    protocol:
      name: dubbo
      port: -1
    scan:
      base-packages: com.xxxx.manager.service
mybatis:
  type-aliases-package: com.xxxx.manager.pojo
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.xxx.manager.mapper: debug
goods.category.list.key: goods:category:list:goodsCategoryList
user.ticket: user:userTicket
